project:
  type: book

book:
  title: "R Development Guide"
  author: "R Contribution Working Group"
  date: today
  favicon: img/favicon.png
  site-url: https://contributor.r-project.org/rdevguide
  repo-url: https://github.com/r-devel/rdevguide
  repo-branch: main
  repo-actions: [edit, issue]
  sharing: [linkedin]
  open-graph: true
  image: img/cover_page_scriberia.png
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - chapters/introduction.qmd
    - chapters/getting_started.qmd
    - chapters/issue_tracking.qmd
    - chapters/reporting_bugs.qmd
    - chapters/submitting_feature_requests.qmd
    - chapters/reviewing_bugs.qmd                
    - chapters/finding_the_source.qmd             
    - chapters/lifecycle_of_a_patch.qmd
    - chapters/documenting.qmd                    
    - chapters/message_translations.qmd         
    - chapters/testing_pre_release_r_versions.qmd
    - chapters/r_core_developers.qmd
    - chapters/where_to_get_help.qmd              
    - chapters/news_and_announcements.qmd   
    - chapters/developer_tools.qmd             

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, css/theme-dark.scss]
    include-in-header: html/header.html
    description-meta: "This guide is a comprehensive resource for contributors (from all levels, beginners, intermediate, and seasoned) to the R project, facilitating their onboarding and helping them navigate the contribution process."
  pdf:
    documentclass: scrreprt
    include-in-header: tex/preamble.tex
    include-before-body: tex/frontpage.tex
  epub:
    cover-image: img/cover_page_scriberia.png

# book_filename: "rdevguide"
# chapter_name: "Chapter "
# repo: https://github.com/r-devel/rdevguide
# url: 'https\://contributor.r-project.org/rdevguide/'
# github-repo: "r-devel/rdevguide"
# output_dir: docs
# clean: [packages.bib, bookdown.bbl]
# new_session: yes
# edit: https://github.com/r-devel/rdevguide/edit/main/%s
# delete_merged_file: true
